### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by louislang** [mre/sedre#1]
Just saw this package come through the [Phylum](https://phylum.io) pipeline as a Crate typosquat. Thought "not again..." pleasantly surprised to see it was a preemptive attempt to prevent additional typosquats. Glad to see people taking a proactive role in helping clean up and protect these ecosystems! ❤️

**Comment by mre** [comment]
Thanks! To be honest, I would not trust a single maintainer to handle this responsibility. It might be better to move this crate to the rust GitHub organization and add more "maintainers". I have not talked with anyone from the leadership team, but I'd be thankful for suggestions. Ideally, this should be solved on the crates.io level and through an approval process for each critical crate.

**Comment by louislang** [comment]
Totally agree! Typosquat identification is a surprisingly _difficult_ problem. Nonetheless, happy to see some proactive measures from the community.

**Comment by mre** [comment]
Thanks for the kind words. Closing this. Let's stay in touch, though. 😊
